### ISSUE TITLE
Tests are failed

### ISSUE THREAD

**Issue by gEndelf** [SC5/serverless-messenger-boilerplate#8]
Some tests are broken. The reason is - requested session is not available in DynamoDB

```
serverless invoke test -f facebookBot                                                                                  


  Facebook bot service
    Verify token
      ✓ Gives challenge given the right verify token
      ✓ Gives an error given an invalid verify token
    Receive / Send messages
ERROR (receiveEvent): ResourceNotFoundException: Requested resource not found
Error: ResourceNotFoundException: Requested resource not found

  Assertion Error ----------------------------------------

     expected undefined to match /witAiTopic/

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.8.0
     Serverless Version: 1.10.1
```

---

```
serverless invoke test -f witAiHandler                                                                                  

  witAiHandler
wit.ai error { ResourceNotFoundException: Requested resource not found
    at Request.extractError (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/request.js:675:12)
    at Request.callListeners (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/request.js:675:12)
    at Request.callListeners (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/event_listeners.js:244:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  message: 'Requested resource not found',
  code: 'ResourceNotFoundException',
  time: 2017-04-08T09:23:22.131Z,
  requestId: 'QJ74TA648I8TNJSJ39NEGKS2IVVV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 32.62918610321752 }
    1) Send text to Wit.ai (via SNS) and receive a response

  My bot
wit.ai error { ResourceNotFoundException: Requested resource not found
    at Request.extractError (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/request.js:675:12)
    at Request.callListeners (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/request.js:675:12)
    at Request.callListeners (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/Users/bb/prj/bots/weather-bot/node_modules/aws-sdk/lib/event_listeners.js:244:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  message: 'Requested resource not found',
  code: 'ResourceNotFoundException',
  time: 2017-04-08T09:23:24.698Z,
  requestId: 'TMDQ11HF6HTRRB7I0OPINVFFTBVV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 41.51889386791292 }
    2) Handles some user input


  0 passing (5s)
  2 failing

  1) witAiHandler Send text to Wit.ai (via SNS) and receive a response:
     Error: done() invoked with non-Error: TOPIC_NOT_FOUND: Bot-fbMessengerTopic-dev
      at wrapped.run (test/witAiHandler.js:53:16)
      at messageQueue.getMessage.then.then.then.catch.error (wit-ai/handler.js:24:23)
      at process._tickDomainCallback (internal/process/next_tick.js:135:7)

  2) My bot Handles some user input:
     Error: done() invoked with non-Error: TOPIC_NOT_FOUND: Bot-fbMessengerTopic-dev
      at wrapped.run (test/witAiHandler.js:75:16)
      at messageQueue.getMessage.then.then.then.catch.error (wit-ai/handler.js:24:23)
      at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

**Comment by gEndelf** [comment]
@mpuittinen could you fix plz?
